name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  id-token: write

jobs:
  test-app:
    name: Test Next.js App
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.13.1' 

      - name: Install Dependencies
        run: npm install --force

      - name: Run tests
        run: npm test

      - name: Run build
        run: npm run build

  test-llm:
    name: Test Python LLM API
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./llm
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest 

  deploy-app:
    name: Deploy App to Vercel
    runs-on: ubuntu-latest
    needs: test-app
    if: success()
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.13.1'

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information for Production
        run: vercel pull ./app --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts for Production
        run: vercel build ./app --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel Production
        run: vercel deploy ./app --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

  deploy-llm:
    name: Deploy LLM API to Cloud Run
    runs-on: ubuntu-latest
    needs: test-llm
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Autenticación con Google Cloud usando Workload Identity Federation (recomendado)
      # Asegúrate de haber configurado Workload Identity Federation en GCP
      # https://github.com/google-github-actions/auth
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}' # Utiliza la clave de la cuenta de servicio

      # Configurar gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # Opcional: Configurar Docker para autenticarse con Google Artifact Registry (si usas GAR)
      # - name: Configure Docker
      #   run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

      # Construir y subir la imagen Docker (usando Cloud Build o Docker directamente)
      # Ejemplo usando Cloud Build (requiere permisos de Cloud Build en la SA)
      - name: Build and Push Docker image with Cloud Build
        run: |
          gcloud builds submit ./llm --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_SERVICE_NAME }}:latest

      # Desplegar la imagen a Cloud Run
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ secrets.GCP_SERVICE_NAME }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          region: ${{ secrets.GCP_REGION }}
          # Usa la imagen construida previamente (asegúrate que la etiqueta coincida)
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_SERVICE_NAME }}:latest
          # Opcional: Pasa variables de entorno desde secretos de GitHub a Cloud Run
          # env_vars: |
          #   OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY_SECRET_NAME }}
          #   GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY_SECRET_NAME }}

      # Opcional: Mostrar la URL del servicio desplegado
      - name: Show deployed URL
        run: echo "Deployed to ${{ steps.deploy.outputs.url }}" 